In [8]:
import pandas as pd

url = "https://raw.githubusercontent.com/DanieltheAnalyst1/Financial_Data_Analysis-SQL/main/Finance_data.csv"
df = pd.read_csv(url)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   gender                             40 non-null     object
 1   age                                40 non-null     int64
 2   Investment_Avenues                 40 non-null     object
 3   Mutual_Funds                       40 non-null     int64
 4   Equity_Market                      40 non-null     int64
 5   Debentures                         40 non-null     int64
 6   Government_Bonds                   40 non-null     int64
 7   Fixed_Deposits                     40 non-null     int64
 8   PPF                                40 non-null     int64
 9   Gold                               40 non-null     int64
 10  Stock_Marktet                      40 non-null     object
 11  Factor                             40 non-null     object
 12  Objective                          40 non-null     object
 13  Purpose                            40 non-null     object
 14  Duration                           40 non-null     object
 15  Invest_Monitor                     40 non-null     object
 16  Expect                             40 non-null     object
 17  Avenue                             40 non-null     object
 18  What are your savings objectives?  40 non-null     object
 19  Reason_Equity                      40 non-null     object
 20  Reason_Mutual                      40 non-null     object
 21  Reason_Bonds                       40 non-null     object
 22  Reason_FD                          40 non-null     object
 23  Source                             40 non-null     object
dtypes: int64(8), object(16)
memory usage: 7.6+ KB

In [9]:
df.head()

,gender,age,Investment_Avenues,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold,...,Duration,Invest_Monitor,Expect,Avenue,What are your savings objectives?,Reason_Equity,Reason_Mutual,Reason_Bonds,Reason_FD,Source
0,Female,34,Yes,1,2,5,3,7,6,4,...,1-3 years,Monthly,20%-30%,Mutual Fund,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Fixed Returns,Newspapers and Magazines
1,Female,23,Yes,4,3,2,1,5,6,7,...,More than 5 years,Weekly,20%-30%,Mutual Fund,Health Care,Dividend,Better Returns,Safe Investment,High Interest Rates,Financial Consultants
2,Male,30,Yes,3,6,4,2,5,1,7,...,3-5 years,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Tax Benefits,Assured Returns,Fixed Returns,Television
3,Male,22,Yes,2,1,3,7,6,4,5,...,Less than 1 year,Daily,10%-20%,Equity,Retirement Plan,Dividend,Fund Diversification,Tax Incentives,High Interest Rates,Internet
4,Female,24,No,2,1,3,6,4,5,7,...,Less than 1 year,Daily,20%-30%,Equity,Retirement Plan,Capital Appreciation,Better Returns,Safe Investment,Risk Free,Internet

In [10]:
print(df.columns.tolist())

['gender', 'age', 'Investment_Avenues', 'Mutual_Funds', 'Equity_Market', 'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold', 'Stock_Marktet', 'Factor', 'Objective', 'Purpose', 'Duration', 'Invest_Monitor', 'Expect', 'Avenue', 'What are your savings objectives?', 'Reason_Equity', 'Reason_Mutual', 'Reason_Bonds', 'Reason_FD', 'Source']

In [11]:
import plotly.express as px

gender_counts = df['gender'].value_counts().reset_index()
gender_counts.columns = ['gender', 'count']

fig = px.pie(gender_counts, names='gender', values='count',
             title='Gender Distribution of Survey Participants',
             color_discrete_sequence=['#FF69B4', '#4682B4'])
fig.update_traces(textinfo='percent+label')
fig.show()

In [12]:
fig2 = px.bar(gender_counts, x='gender', y='count',
              title='Gender Distribution - Bar Chart',
              color='gender', text='count')
fig2.show()

In [32]:
import pandas as pd
from IPython.display import display, HTML

numerical_cols = ['age', 'Mutual_Funds', 'Equity_Market', 'Debentures',
                   'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']

desc_stats = df[numerical_cols].describe().T
desc_stats['median'] = df[numerical_cols].median()
desc_stats = desc_stats[['mean', 'median', 'std', 'min', 'max']]

styled_stats = desc_stats.style.background_gradient(cmap='Blues', subset=['mean', 'median'])\
    .format(precision=2)\
    .set_caption("Descriptive Statistics: Age & Investment Preference Ranks")\
    .set_table_styles([
        {'selector': 'th, td', 'props': [('border', '1px solid #ddd'), ('padding', '8px'), ('text-align', 'center')]},
        {'selector': 'caption', 'props': [('font-size', '16px'), ('font-weight', 'bold'), ('color', '#2F4F4F'), ('padding-bottom', '10px')]},
        {'selector': 'th', 'props': [('background-color', '#4682B4'), ('color', 'white')]}
    ])

display(styled_stats)

In [7]:
avenue_counts = df['Avenue'].value_counts().reset_index()
avenue_counts.columns = ['Avenue', 'Count']

print(avenue_counts)

fig = px.bar(avenue_counts, x='Avenue', y='Count',
             title='Most Preferred Investment Avenue',
             color='Avenue', text='Count')
fig.show()

                  Avenue  Count
0            Mutual Fund     18
1                 Equity     10
2         Fixed Deposits      9
3  Public Provident Fund      3

In [14]:
avg_ranks = df[['Mutual_Funds', 'Equity_Market', 'Debentures',
                 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']].mean().sort_values()

print("Average Preference Rank (lower = more preferred):")
print(avg_ranks)

fig2 = px.bar(x=avg_ranks.index, y=avg_ranks.values,
              title='Average Preference Rank by Investment Type (Lower = More Preferred)',
              labels={'x': 'Investment Type', 'y': 'Average Rank'})
fig2.show()

Average Preference Rank (lower = more preferred):
PPF                 2.025
Mutual_Funds        2.550
Equity_Market       3.475
Fixed_Deposits      3.575
Government_Bonds    4.650
Debentures          5.750
Gold                5.975
dtype: float64

In [15]:
savings_counts = df['What are your savings objectives?'].value_counts().reset_index()
savings_counts.columns = ['Savings_Objective', 'Count']

print(savings_counts)

fig = px.bar(savings_counts, x='Savings_Objective', y='Count',
             title='Main Savings Objectives Among Participants',
             color='Savings_Objective', text='Count')
fig.show()

  Savings_Objective  Count
0   Retirement Plan     24
1       Health Care     13
2         Education      3

In [16]:
source_counts = df['Source'].value_counts().reset_index()
source_counts.columns = ['Source', 'Count']

print(source_counts)

fig = px.bar(source_counts, x='Source', y='Count',
             title='Sources of Investment Information',
             color='Source', text='Count')
fig.show()

                     Source  Count
0     Financial Consultants     16
1  Newspapers and Magazines     14
2                Television      6
3                  Internet      4

In [17]:
fig2 = px.pie(source_counts, names='Source', values='Count',
              title='Information Sources - Proportion')
fig2.update_traces(textinfo='percent+label')
fig2.show()

In [18]:
duration_counts = df['Duration'].value_counts().reset_index()
duration_counts.columns = ['Duration', 'Count']
print(duration_counts)

# Map duration categories to approximate numeric years (midpoint)
duration_map = {
    'Less than 1 year': 0.5,
    '1-3 years': 2,
    '3-5 years': 4,
    'More than 5 years': 6
}

df['Duration_Years'] = df['Duration'].map(duration_map)

avg_duration = df['Duration_Years'].mean()
print(f"\nAverage Investment Duration: {avg_duration:.2f} years")

            Duration  Count
0          3-5 years     19
1          1-3 years     18
2   Less than 1 year      2
3  More than 5 years      1

Average Investment Duration: 2.98 years

In [19]:
fig = px.bar(duration_counts, x='Duration', y='Count',
             title='Investment Duration Distribution',
             color='Duration', text='Count')
fig.show()

In [20]:
print(df['Duration'].unique())

['1-3 years' 'More than 5 years' '3-5 years' 'Less than 1 year']

In [29]:
import pandas as pd

corr_cols = ['age', 'Duration_Years', 'Mutual_Funds', 'Equity_Market',
             'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']

corr_matrix = df[corr_cols].corr()

# Styled box-like table with color gradient
styled_corr = corr_matrix.style.background_gradient(cmap='RdBu_r', vmin=-1, vmax=1)\
    .format(precision=2)\
    .set_caption("Correlation Matrix: Age, Duration & Investment Preferences")\
    .set_properties(**{'border': '1px solid #ddd', 'text-align': 'center'})

styled_corr

In [22]:
fig2 = px.scatter(df, x='age', y='Duration_Years',
                   title='Age vs Investment Duration',
                   trendline='ols')
fig2.show()

In [31]:
from IPython.display import display, HTML

reason_cols = ['Reason_Equity', 'Reason_Mutual', 'Reason_Bonds', 'Reason_FD']

colors = ['#4682B4', '#2E8B57', '#B8860B', '#8B4789']

html = """
<div style="border:2px solid #333; border-radius:10px; padding:20px; background-color:#fafafa; width:fit-content; color:#000;">
<h3 style="margin-top:0; color:#2F4F4F;">💡 Reasons for Investment by Instrument</h3>
"""

for i, col in enumerate(reason_cols):
    counts = df[col].value_counts()
    color = colors[i % len(colors)]
    html += f"""
    <div style="margin-bottom:15px; padding:10px; border-left:5px solid {color}; background-color:#ffffff;">
    <h4 style="margin:0 0 8px 0; color:{color};">{col.replace('_', ' ')}</h4>
    <ul style="margin:0; padding-left:20px;">
    """
    for reason, count in counts.items():
        html += f"<li style='color:#000000; margin-bottom:4px;'>{reason}: <b style='color:{color};'>{count}</b></li>"
    html += "</ul></div>"

html += "</div>"
display(HTML(html))

In [24]:
import plotly.express as px
import pandas as pd

reason_summary = pd.DataFrame({
    col: df[col].value_counts() for col in reason_cols
}).fillna(0)

fig = px.bar(reason_summary.T, barmode='group',
             title='Reasons for Investment by Instrument Type',
             labels={'value': 'Count', 'index': 'Investment Type'})
fig.show()

In [25]:
expect_counts = df['Expect'].value_counts().reset_index()
expect_counts.columns = ['Expected_Return', 'Count']
print(expect_counts)

fig2 = px.bar(expect_counts, x='Expected_Return', y='Count',
              title='Expected Returns from Investments',
              color='Expected_Return', text='Count')
fig2.show()

  Expected_Return  Count
0         20%-30%     32
1         30%-40%      5
2         10%-20%      3

In [26]:
fig3 = px.pie(expect_counts, names='Expected_Return', values='Count',
              title='Expected Return Distribution')
fig3.update_traces(textinfo='percent+label')
fig3.show()